"use client";

import { useState } from "react";
import { X, Layers, Database, FileText, Brain, Play, HelpCircle, HardDrive } from "lucide-react";

const TABS = [
  { id: "artifacts", label: "Artifacts", Icon: Layers },
  { id: "files", label: "Files", Icon: FileText },
  { id: "sources", label: "Sources", Icon: Database },
  { id: "memory", label: "Memory", Icon: Brain },
  { id: "tools", label: "Tools", Icon: Play },
  { id: "model", label: "Model Info", Icon: HelpCircle },
];

export default function ContextPanel({ onClose }: { onClose: () => void }) {
  const [activeTab, setActiveTab] = useState("artifacts");

  return (
    <aside className="context-panel" style={{ width: "var(--context-w)" }}>
      <div className="context-panel-header">
        <span style={{ fontWeight: 600, fontSize: "14px", display: "flex", alignItems: "center", gap: "8px" }}>
          <HardDrive size={16} style={{ color: "var(--primary)" }} />
          Workspace Context
        </span>
        <button className="icon-btn sm" onClick={onClose} title="Close panel">
          <X size={16} />
        </button>
      </div>

      <div className="context-tabs">
        {TABS.map(({ id, label, Icon }) => (
          <button
            key={id}
            className={`context-tab ${activeTab === id ? "active" : ""}`}
            onClick={() => setActiveTab(id)}
            title={label}
            style={{ display: "flex", alignItems: "center", gap: "4px" }}
          >
            <Icon size={13} />
            <span>{label}</span>
          </button>
        ))}
      </div>

      <div className="context-body">
        {activeTab === "artifacts" && (
          <div className="context-empty">
            <Layers size={32} style={{ opacity: 0.3 }} />
            <p style={{ margin: 0, fontWeight: 500 }}>No active artifacts</p>
            <p style={{ margin: 0, fontSize: "12px", color: "var(--text-muted)" }}>
              Artifacts (code, diagrams, reports) generated by the assistant will appear here.
            </p>
          </div>
        )}

        {activeTab === "files" && (
          <div className="context-empty">
            <FileText size={32} style={{ opacity: 0.3 }} />
            <p style={{ margin: 0, fontWeight: 500 }}>No files uploaded</p>
            <p style={{ margin: 0, fontSize: "12px", color: "var(--text-muted)" }}>
              Upload documents (PDF, TXT, DOCX) to add them to this project's context.
            </p>
          </div>
        )}

        {activeTab === "sources" && (
          <div className="context-empty">
            <Database size={32} style={{ opacity: 0.3 }} />
            <p style={{ margin: 0, fontWeight: 500 }}>No search sources retrieved</p>
            <p style={{ margin: 0, fontSize: "12px", color: "var(--text-muted)" }}>
              When RAG is used, references and text snippets will be listed here.
            </p>
          </div>
        )}

        {activeTab === "memory" && (
          <div className="context-empty">
            <Brain size={32} style={{ opacity: 0.3 }} />
            <p style={{ margin: 0, fontWeight: 500 }}>Memory is empty</p>
            <p style={{ margin: 0, fontSize: "12px", color: "var(--text-muted)" }}>
              Key user preferences and facts will display here to guide future messages.
            </p>
          </div>
        )}

        {activeTab === "tools" && (
          <div className="context-empty">
            <Play size={32} style={{ opacity: 0.3 }} />
            <p style={{ margin: 0, fontWeight: 500 }}>No tool executions yet</p>
            <p style={{ margin: 0, fontSize: "12px", color: "var(--text-muted)" }}>
              Summaries of executed actions (calculators, python script runs) will log here.
            </p>
          </div>
        )}

        {activeTab === "model" && (
          <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
            <div style={{ padding: "12px", borderRadius: "var(--radius-md)", border: "1px solid var(--border)", background: "var(--surface-secondary)" }}>
              <h3 style={{ margin: "0 0 8px 0", fontSize: "14px", fontWeight: 600 }}>Active Model: Nexora Native</h3>
              <p style={{ margin: "0 0 6px 0", fontSize: "12px", color: "var(--text-secondary)" }}>
                A 100% scratch-built Transformer model trained locally inside this repository.
              </p>
              <div style={{ display: "flex", flexDirection: "column", gap: "4px", fontSize: "11px", fontFamily: "var(--font-mono)", color: "var(--text-muted)" }}>
                <div>d_model: 256</div>
                <div>n_layers: 6</div>
                <div>n_heads: 8</div>
                <div>vocab_size: 8,000</div>
                <div>max_seq_len: 256</div>
                <div>weight_decay: 0.01</div>
              </div>
            </div>
            <div style={{ fontSize: "12px", color: "var(--text-muted)", padding: "0 4px" }}>
              Note: This is a research CPU-optimized network. To increase performance or vocabulary, run a training run with custom configurations.
            </div>
          </div>
        )}
      </div>
    </aside>
  );
}
